{
 "title": "Pure Storage FlashBlade - Overview",
 "tags": [
  "pure storage",
  "flashblade",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DashboardVersion", "query": "${VAR_DASHBOARDVERSION}" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "env", "label": "Env", "query": { "query": "label_values(purefb_info, env)" } },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": {
     "query": "label_values(purefb_info, instance)"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "1,2,3,4,5,6,8,10,15,20,25,50" },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "query_result(purefb_array_performance_latency_usec)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.purestorage.com/content/dam/purestorage/knowledge/pure-storage.png.imgo.png\">"
   }
  },
  {
   "title": "FlashBlade Array System Detail",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(purefb_info{instance=~\"$instance\",env=~\"$env\"}) by (instance, os, version)",
     "legendFormat": "{{os}} {{version}}"
    },
    {
     "expr": "min(purefb_hardware_health{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "Hardware Health"
    },
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "Number of Alerts"
    },
    {
     "expr": "avg(purefb_array_space_data_reduction_ratio{instance=~\"$instance\",env=~\"$env\",type=\"array\"}) by (instance)",
     "legendFormat": "Ratio"
    },
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",type=\"array\",space=\"capacity\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Array Capacity (TB)"
    },
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",type=\"array\",space=\"empty\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Array Free Space"
    },
    {
     "expr": "purefb_array_space_utilization{env=~\"$env\", instance=~\"$instance\"}",
     "legendFormat": "Utililzation"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "options": {
    "content": "# **PURE** STORAGE\n\n## Overview\n\nThis dashboard provides performance and capacity details for Pure Storage FlashBlades.\nGroup arrays by customer defined environment, whole fleets, or view arrays individually."
   }
  },
  {
   "title": "FlashBlade Array Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\",severity=\"critical\",env=~\"$env\"}) by (instance) OR on() sum(purefb_alerts_open{instance=~\"$instance\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\",severity=\"warning\",env=~\"$env\"}) by (instance) OR on() sum(purefb_alerts_open{instance=~\"$instance\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\",severity=\"info\",env=~\"$env\"}) by (instance) OR on() sum(purefb_alerts_open{instance=~\".*\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\",severity=\".*\",env=~\"$env\"}) by (instance) OR on() sum(purefb_alerts_open{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 42, "w": 6, "x": 0, "y": 9 },
   "options": {
    "content": "## Metrics\n\n`All metrics are prefixed with purefb_`\n\nBelow are the metrics names available:\n\n### Collected with endpoint /metrics/array\n\n    * info\n    * alerts_open\n    * hardware_health\n    * array_http_specific_performance_latency_usec\n    * array_http_specific_performance_throughput_iops\n    * array_nfs_latency_usec\n    * array_nfs_throughput_iops\n    * array_performance_average_bytes\n    * array_performance_bandwidth_bytes\n    * array_performance_latency_usec\n    * array_performance_throughput_iops\n    * array_s3_specific_performance_latency_usec\n    * array_s3_specific_performance_throughput_iops\n    * array_space_bytes\n    * array_space_data_reduction_ratio\n    * array_space_parity\n    * bucket_replica_links_lag_msec\n    * buckets_performance_average_bytes\n    * buckets_performance_bandwidth_bytes\n    * buckets_performance_latency_usec\n    * buckets_performance_throughput_iops\n    * buckets_s3_specific_performance_latency_usec\n    * buckets_s3_specific_performance_throughput_iops\n    * buckets_space_bytes\n    * buckets_space_data_reduction_ratio\n    * buckets_space_objects\n    * file_system_links_lag_msec\n    * file_systems_performance_average_bytes\n    * file_systems_performance_bandwidth_bytes\n    * file_systems_performance_latency_usec\n    * file_systems_performance_throughput_iops\n    * file_systems_space_bytes\n    * file_systems_space_data_reduction_ratio\n    * hardware_connectors_performance_bandwidth_bytes\n    * hardware_connectors_performance_errors\n    * hardware_connectors_performance_throughput_pkts\n\n### Collected with endpoint /metrics/usage\n    * file_system_usage_groups_bytes\n    * file_system_usage_users_bytes\n    \n### Collected with endpoint /metrics/clients\nCollecting client performance information may require increasing scrape collection it is therefore recommended as an optional configuration item.\n \n    * array_clients_performance_avg_size_bytes\n    * array_clients_performance_bandwidth_bytes\n    * array_clients_performance_latency_usec\n    * array_clients_performance_throughput_iops\n\n\n\n"
   }
  },
  {
   "title": "Total Array Space Utilization by Type and $instance arrays(s)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=~\"total_physical\",type!=\"array\"}) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=~\"snapshots\"}) by (space)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=~\"empty\"}) by (space)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average IOPS by IO Type and $instance arrays(s)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefb_array_performance_throughput_iops{instance=~\"$instance\",env=~\"$env\"}[$__range])) by (dimension)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average IOPS by Protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefb_array_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\",protocol!=\"all\"}[$__range])) by (protocol)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Throughput by $instance array(s) &  $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "purefb_array_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\", dimension=\"read_bytes_per_sec\", protocol=~\"$protocol\"}\nand\ntopk($TopItems, rate(purefb_array_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\", dimension=\"read_bytes_per_sec\", protocol=~\"$protocol\"}[$__range] @ end() ))",
     "legendFormat": "{{instance}} - {{protocol}}"
    }
   ]
  },
  {
   "title": "Write Throughput by $instance array(s) & $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "purefb_array_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\", dimension=\"write_bytes_per_sec\", protocol=~\"$protocol\"}\nand\ntopk($TopItems, rate(purefb_array_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\", dimension=\"write_bytes_per_sec\", protocol=~\"$protocol\"}[$__range] @ end() ))",
     "legendFormat": "{{instance}} - {{protocol}}"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Filesystems Throughput by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(purefb_file_systems_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\"}) by (name,instance, dimension)\nand\ntopk($TopItems, avg(rate(purefb_file_systems_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\"}[$__range] @ end() )) by (name,instance, dimension))",
     "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
    }
   ]
  },
  {
   "title": "Average Top $TopItems File System Latency by Name & IO Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(purefb_file_systems_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}) by (name,dimension,instance)\nand\ntopk($TopItems, avg(rate(purefb_file_systems_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}[$__range] @ end() )) by (name,dimension,instance))",
     "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Buckets Throughput $instance arrays(s) by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(purefb_buckets_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\"}) by (name,instance,dimension)\nand\ntopk($TopItems, avg(rate(purefb_buckets_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\"}[$__range] @ end() )) by (name,instance,dimension))",
     "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Latent Buckets $instance arrays(s) by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(purefb_buckets_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}) by (name,dimension,instance)\nand\ntopk($TopItems, avg(rate(purefb_buckets_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}[$__range] @ end() )) by (name,dimension,instance))",
     "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
    }
   ]
  },
  {
   "title": "Average Total Latency by $instance array(s) and $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefb_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_read_op\"}[$__interval]))",
     "legendFormat": "usec_per_read_op"
    },
    {
     "expr": "sum(avg_over_time(purefb_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_write_op\"}[$__interval]))",
     "legendFormat": "usec_per_write_op"
    },
    {
     "expr": "sum(avg_over_time(purefb_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_other_op\"}[$__interval]))",
     "legendFormat": "usec_per_other_op"
    }
   ]
  },
  {
   "title": "IOPS by $instance array(s) and $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefb_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"reads_per_sec\"}[$__interval]))",
     "legendFormat": "reads_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefb_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"writes_per_sec\"}[$__interval]))",
     "legendFormat": "writes_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefb_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"other_per_sec\"}[$__interval]))",
     "legendFormat": "other_per_sec"
    }
   ]
  },
  {
   "title": "Average Total Bandwidth by $instance array(s) and $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefb_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\",dimension=\"read_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "read_bytes_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefb_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\",dimension=\"write_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "write_bytes_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefb_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\",dimension=\"other_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "other_bytes_per_sec"
    }
   ]
  }
 ]
}