apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
  labels:
    app: grafana
spec:
  storageClassName: px-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
