apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: px-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
